version: '3.3'
services:
    php:
        ports:
            - '80:80'
            - '3306:3306'
        volumes:
            - '${PWD}:/var/www/html/biblioFRD-Server'
        restart: on-failure
        logging:
            options:
                max-size: 1g
        image: 'php:8.0.28-apache'